FashionShop/FashionShop/Areas/Admin/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.ADO;
using Model.EF;

namespace FashionShop.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        // GET: Admin/Product
        public ActionResult Index(int page = 1, int pageSize = 3)
        {
            int totalRecord = 0;
            var model = new ProductADO().GetAllProductsForAdmin(ref totalRecord, page, pageSize);

            // Tổng bản ghi Lấy từ DB / số sp muốn hiển thị 
            int totalPage = 0;
            totalPage = (int)Math.Ceiling((double)(totalRecord / pageSize));

            int displayMaxPages = 6;
            ViewBag.DisplayMaxPages = displayMaxPages;
            ViewBag.StartIndex = page;
            ViewBag.TotalPage = totalPage;
            ViewBag.Next = page + 1;
            ViewBag.Prev = page - 1;
            return View(model);
        }

        public void DropDownListCategory(int? selectedId = null)
        {
            var model = new ProductCategoryADO();
            ViewBag.CategoryId = new SelectList(model.GetListProductCategory(), "prd_category_id", "prd_category_name", selectedId);
        }

        [HttpGet]
        public ActionResult AddProduct()
        {
            DropDownListCategory();
            return View();
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult AddProduct(product entity)
        {
            if (ModelState.IsValid)
            {
                entity.created_date = DateTime.Now;
                entity.status = true;
                var result = new ProductADO().Insert(entity);
                if (result > 0)
                {
                    SetAlert("Thêm mới thành công!", "success");
                    return Redirect("/Admin/quan-ly-san-pham");
                }
                else
                {
                    ModelState.AddModelError("", "Thêm mới không thành công!");
                }
            }
            DropDownListCategory();
            return View();
        }

        public JsonResult RemoveProduct(int id)
        {
            try
            {
                new ProductADO().Remove(id);
                return Json(new
                {
                    message = 1
                });
            }
            catch (Exception)
            {
                return Json(new
                {
                    message = 0
                });
            }
        }

        [HttpGet]
        public ActionResult EditProduct(int id)
        {
            DropDownListCategory();
            var model = new ProductADO().GetProductId(id);
            return View(model);
        }

        [HttpPost, ValidateInput(false)]
        public ActionResult EditProduct(product prdEntity)
        {
            if (ModelState.IsValid)
            {
                prdEntity.created_date = DateTime.Now;
                prdEntity.status = true;
                var result = new ProductADO().Update(prdEntity);
                if (result)
                {
                    SetAlert("Cập nhật sản phẩm thành công!", "success");
                    return Redirect("/Admin/quan-ly-san-pham");
                }
                else
                {
                    ModelState.AddModelError("", "Cập nhật không thành công!");
                }
            }
            DropDownListCategory();
            return View();
            // return Redirect("/Admin/quan-ly-san-pham");
        }
    }
}

FashionShop/FashionShop/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.ADO;

namespace FashionShop.Controllers
{
    public class ProductCategoryController : Controller
    {
        // GET: ProductCategory
        [ChildActionOnly]
        public ActionResult _ProductCategoryPartial()
        {
            var model = new ProductCategoryADO().GetListProductCategory();
            return PartialView(model);
        }
    }
}

FashionShop/FashionShop/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model.ADO;

namespace FashionShop.Controllers
{
    public class ProductController : Controller
    {
        // Ghi comment vào đầu hàm theo format dưới đây: 
        // Ghi rõ parameter được dùng cho (i)input hay (o)output hay sử dụng cho cả 2 (i/o)input và output
        /****************************************************************/
        /* Function Name : GetStatus()                                  */
        /* Function      : 状態を取得する                               */
        /* Param         : nStateID(i) 状態を取得する部品のID(0～15)    */
        /* Return        : ０ ： 正常な状態                             */
        /*               : １ ： エラー有り                             */
        /* Create        : S.Sato 1999/09/09                            */
        /* Update        :                                              */
        /* Comment       :                                              */
        /****************************************************************/
        public ActionResult _ListNewProductsPartial()
        {
            var model = new ProductADO().GetListNewProducts(8);
            return PartialView(model);
        }

        public ActionResult _ListDiscountProductsPartial()
        {
            var model = new ProductADO().GetListDiscountProducts(8);
            return PartialView(model);
        }

        // totalItems (required) - the total number of items to be paged
        // currentPage (optional) - the current active page, default to first page
        // pageSize (optional) - the number of items per page, defaults to 10
        // maxPages (optional) - the maximum number of page navigation link to display, defaul to 7
        public ActionResult ListAllProducts(int nPage = 1, int nPageSize = 4)// pageSize = productsPerPage
        {
            int nTotalRecord = 0;
            var model = new ProductADO().GetAllProducts(ref nTotalRecord, nPage, nPageSize);

            ViewBag.TotalRecord = nTotalRecord;
            ViewBag.StartIndex = nPage;

            int totalPage = 0;
            int displayMaxPages = 6;

            // Tổng trang của số bản ghi / số lượng sp hiển thị 
            totalPage = (int)Math.Ceiling((double)nTotalRecord / nPageSize); // Math.Ceiling(double a) -> ham lam tron so len
            ViewBag.TotalPage = totalPage;
            ViewBag.DisplayMaxPages = displayMaxPages;
            ViewBag.Next = nPage + 1;
            ViewBag.Prev = nPage - 1;

            return View(model);
        }

        /****************************************************************/
        /* Function Name : ListProductsByCategory()                   
        /* Function      : List of products by category               
        /* Param         : nCategoryId(i) category id to return the product list                                
        /* Return        : model ： return a product objet                 
        /* Create        : T.Khai 2021/01/11                            
        /* Update        :                                              
        /* Comment       :  
        /****************************************************************/
        public ActionResult ListProductsByCategory(int nCategoryId)
        {
            var model = new ProductADO().GetListProductsByCategoryId(nCategoryId);
            return View(model);
        }

        /****************************************************************/
        /* Function Name : ViewProductDetails()                   
        /* Function      : View product details               
        /* Param         : nPrdId(i) Product id to return                                 
        /* Return        : model ： return a record (1 hàng)                  
        /* Create        : T.Khai 2020/12/23                            
        /* Update        :                                              
        /* Comment       :  
        /****************************************************************/
        public ActionResult ViewProductDetails(int nPrdId)
        {
            var model = new ProductADO().GetProductId(nPrdId);
            return View(model);
        }

        /****************************************************************/
        /* Function Name : _ListRelatedProductsPartial()                   
        /* Function      : List of related products              
        /* Param         : nPrdId(i) Product id                                
        /* Return        : listRecords ： return list of records                  
        /* Create        : T.Khai 2020/12/23                            
        /* Update        :                                              
        /* Comment       :  
        /****************************************************************/
        [ChildActionOnly]
        public ActionResult _ListRelatedProductsPartial(int nPrdId)
        {
            var listRecords = new ProductADO().GetListRelatedProducts(nPrdId);
            return PartialView(listRecords);
        }

        /****************************************************************/
        /* Function Name   : ListProductName()                   
        /* Function Content: List product name              
        /* Param           : sKeyword(i) string key words                                 
        /* Return          : Json ： return list product name in Json Jquery format                
        /* Create          : T.Khai 2020/12/23                            
        /* Update          :                                              
        /* Comment         : Fife jquery: /Contents/js/JsFileController/search-autocomplete  
        /****************************************************************/
        public JsonResult ListProductName(string sKeyword)
        {
            var productName = new ProductADO().GetProductName(sKeyword);
            return Json(new
            {
                data = productName,
                status = true
            }, JsonRequestBehavior.AllowGet);
        }

        /****************************************************************/
        /* Function Name   : Search()                   
        /* Function Content:              
        /* Param           : sKeyword(i), nPage(i), nPageSize(i)                                  
        /* Return          : Model: list all product            
        /* Create          : T.Khai 2021/01/11                            
        /* Update          : T.Khai 2021/01/20
         *                   Fix bug css
        /* Comment         :
        /****************************************************************/
        public ActionResult Search(string sKeyword, int nPage = 1, int nPageSize = 1)// pageSize = productsPerPage
        {
            int nTotalRecord = 0;
            int totalPage = 0;
            int displayMaxPages = 6;
            var model = new ProductADO().GetSearchList(sKeyword, ref nTotalRecord, nPage, nPageSize);
            ViewBag.TotalRecord = nTotalRecord;
            ViewBag.StartIndex = nPage;
            ViewBag.Keyword = sKeyword;

            // Tổng trang của số bản ghi / số lượng sp hiển thị 
            totalPage = (int)Math.Ceiling((double)nTotalRecord / nPageSize); // Math.Ceiling(double a) -> ham lam tron so len
            ViewBag.TotalPage = totalPage;
            ViewBag.DisplayMaxPages = displayMaxPages;
            ViewBag.Next = nPage + 1;
            ViewBag.Prev = nPage - 1;

            return View(model);
        }
    }
}

FashionShop/FashionShop/Views/Product/ListAllProducts.cshtml
@model List<Model.EF.product>
@using Model.EF
@{
    var category = new product_category();
    ViewBag.Title = "Tất cả sản phẩm";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}
<section class="hero hero-page gray-bg padding-small">
    <div class="container">
        <div class="row d-flex">
            <div class="col-lg-9 order-2 order-lg-1">
                <h1>Shop</h1><p class="lead text-muted">@category.prd_category_name</p>
            </div>
            <div class="col-lg-3 text-right order-1 order-lg-2">
                <ul class="breadcrumb justify-content-lg-end">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Shop</li>
                </ul>
            </div>
        </div>
    </div>
</section>

<main>
    <div class="container">
        <div class="row">
            <!-- Sidebar-->
            <div class="sidebar col-xl-3 col-lg-4 sidebar">
                <div class="block">
                    <h6 class="text-uppercase">Danh Mục Sản Phẩm</h6>
                    <ul class="list-unstyled">
                        <li class="active">
                            <a href="#" class="d-flex justify-content-between align-items-center"><span>Danh Mục</span><small></small></a>
                            <ul class="list-unstyled">
                                @Html.Action("_ProductCategoryPartial", "ProductCategory")
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- /Sidebar end-->
            <!-- Grid -->
            <div class="products-grid col-xl-9 col-lg-8 sidebar-left">
                <header class="d-flex justify-content-between align-items-start">
                    <span class="visible-items"> <strong> </strong> <strong> </strong></span>
                    <select id="sorting" class="bs-select">
                        <option value="newest">Mới nhất</option>
                        <option value="oldest">Giảm giá</option>
                        <option value="lowest-price">Giá thấp đến cao</option>
                        <option value="heigh-price">Giá cao đếp thấp</option>
                    </select>
                </header>
                <div class="row">
                    <!-- item-->
                    @foreach (var item in Model)
                    {
                        <div class="item col-xl-4 col-md-6">
                            <div class="product is-gray">
                                <div class="image d-flex align-items-center justify-content-center">
                                    @if (item.discount == null)
                                    {
                                        <div class="ribbon-info text-uppercase">Fresh</div> <!-- Fresh labels-->
                                    }
                                    else
                                    {
                                        <div class="ribbon ribbon-primary text-uppercase">Sale @item.discount%</div> <!-- Discount labels-->
                                    }
                                    <img src="@item.image" alt="product" class="img-fluid">
                                    <div class="hover-overlay d-flex align-items-center justify-content-center">
                                        <div class="CTA d-flex align-items-center justify-content-center">
                                            <a href="/them-vao-gio-hang?productId=@item.product_id&quantity=1" class="add-to-cart"><i class="fa fa-shopping-cart"></i></a>
                                            <a href="/chi-tiet/@item.alias-@item.product_id" class="visit-product active"><i class="icon-search"></i>Xem chi tiết</a>
                                            <a href="#" data-toggle="modal" data-target="#@item.product_id" class="quick-view"><i class="fa fa-arrows-alt"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="title">
                                    @*<small class="text-muted">Tên danh mục</small>*@
                                    <a>
                                        <h3 class="h6 text-uppercase no-margin-bottom">@item.product_name</h3>
                                    </a><span class="price text-muted">@item.price.GetValueOrDefault(0).ToString("N0")<sup>đ</sup></span>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                <!-- Pagination  -->
                @if (ViewBag.TotalPage >= 1)
                {
                    int displayMaxPages = (int)ViewBag.DisplayMaxPages;  // chỉ cho hiển thị chỉ mục 1-6 ptu;
                    int totalPage = (int)ViewBag.TotalPage;  // Total page is display
                    int currentPage = (int)ViewBag.StartIndex;



                    //  Create number links
                    var startPage = Math.Max(1, (currentPage - displayMaxPages) / 2);
                    var endPage = Math.Min(totalPage, (currentPage + displayMaxPages) / 2);

                    var link = "/tat-ca-san-pham";
                    <nav aria-label="page navigation example" class="d-flex justify-content-center">
                        <ul class="pagination pagination-custom">
                            <li class="page-item">
                                <a href="@link?page=@ViewBag.Prev" aria-label="Previous" class="page-link">
                                    <span aria-hidden="true">Prev</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>

                            @for (int i = startPage; i <= endPage; i++)
                            {
                                if (currentPage == i)
                                {
                                    <li class="page-item">
                                        <a href="@link?page=@i" class="page-link active">@i</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="page-item">
                                        <a href="@link?page=@i" class="page-link">@i</a>
                                    </li>
                                }
                            }
                            <li class="page-item">
                                <a href="@link?page=@ViewBag.Next" class="page-link">
                                    <span aria-hidden="true">Next</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        </ul>
                    </nav>

                }
                else
                {
                    <span>Không có bản ghi nào</span>
                }

            </div>
            <!-- / Grid End-->
        </div>
    </div>
</main>

<!-- Modal dialog-->
@foreach (var item in Model)
{
    <div id="@item.product_id" tabindex="-1" role="dialog" aria-hidden="true" class="modal fade overview">
        <div role="document" class="modal-dialog">
            <div class="modal-content">
                <button type="button" data-dismiss="modal" aria-label="Close" class="close">
                    <span aria-hidden="true"><i class="icon-close"></i></span>
                </button>
                <div class="modal-body">
                    @*<div class="ribbon-primary text-uppercase">Sale @item.discount%</div>*@   <!-- discount labels-->
                    <div class="ribbon-info text-uppercase">Fresh</div>
                    <div class="row d-flex align-items-center">
                        <div class="image col-lg-5"><img src="@item.image" alt="..." class="img-fluid d-block"></div>
                        <div class="details col-lg-7">
                            <h2>@item.product_name</h2>
                            <ul class="price list-inline">
                                <li class="list-inline-item current">
                                    @item.price<sup>đ</sup>
                                </li>
                            </ul>
                            <p>@item.description</p>
                            <ul class="CTAs list-inline">
                                <li class="list-inline-item">
                                    <a href="#" class="btn btn-template wide">
                                        <i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng
                                    </a>
                                </li>
                                @*<li class="list-inline-item">
                                        <a href="#" class="visit-product active btn btn-template-outlined wide">
                                            <i class="icon-heart"></i>Yêu thích
                                        </a>
                                    </li>*@
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}



FashionShop/FashionShop/Views/Product/ListProductsByCategory.cshtml
@model List<Model.EF.product>
@using Model.EF;
@{
    var category = new product_category();
    ViewBag.Title = "Sản phẩm theo danh mục";
    Layout = "~/Views/Shared/_LayoutUser.cshtml";
}

<section class="hero hero-page gray-bg padding-small">
    <div class="container">
        <div class="row d-flex">
            <div class="col-lg-9 order-2 order-lg-1">
                <h1>Shop</h1><p class="lead text-muted"></p>
            </div>
            <div class="col-lg-3 text-right order-1 order-lg-2">
                <ul class="breadcrumb justify-content-lg-end">
                    <li class="breadcrumb-item"><a href="/">Home</a></li>
                    <li class="breadcrumb-item active">Shop</li>
                </ul>
            </div>
        </div>
    </div>
</section>
<main>
    <div class="container">
        <div class="row">
            <!-- Sidebar-->
            <div class="sidebar col-xl-3 col-lg-4 sidebar">
                <div class="block">
                    <ul class="list-unstyled">
                        <li class="active">
                            <a href="#" class="d-flex justify-content-between align-items-center"><span>Danh Mục sản phẩm</span><small></small></a>
                            <ul class="list-unstyled">
                                @Html.Action("_ProductCategoryPartial", "ProductCategory")
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
            <!-- /Sidebar end-->
            <!-- Grid -->
            <div class="products-grid col-xl-9 col-lg-8 sidebar-left">
                <header class="d-flex justify-content-between align-items-start">
                    <span class="visible-items"> <strong> </strong> <strong> </strong></span>
                    <select id="sorting" class="bs-select">
                        <option value="newest">Newest</option>
                        <option value="oldest">Oldest</option>
                        <option value="lowest-price">Low Price</option>
                        <option value="heigh-price">High Price</option>
                    </select>
                </header>
                <div class="row">
                    <!-- item-->
                    @foreach (var item in Model)
                    {
                        <div class="item col-xl-4 col-md-6">
                            <div class="product is-gray">
                                <div class="image d-flex align-items-center justify-content-center">
                                    @if (item.discount == null)
                                    {
                                        <div class="ribbon-info text-uppercase">Fresh</div>
                                    }
                                    else
                                    {
                                        <div class="ribbon ribbon-primary text-uppercase">Sale</div>
                                    }
                                    <img src="@item.image" alt="product" class="img-fluid">
                                    <div class="hover-overlay d-flex align-items-center justify-content-center">
                                        <div class="CTA d-flex align-items-center justify-content-center">
                                            <a href="/them-vao-gio-hang?productId=@item.product_id&quantity=1" class="add-to-cart" title="Thêm vào giỏ"><i class="fa fa-shopping-cart"></i></a>
                                            <a href="~/chi-tiet/@item.alias-@item.product_id" class="visit-product active"><i class="icon-search"></i>Xem chi tiết</a>
                                            <a href="#" data-toggle="modal" data-target="#@item.product_id" class="quick-view" title="Xem nhanh"><i class="fa fa-arrows-alt"></i></a>
                                        </div>
                                    </div>
                                </div>
                                <div class="title">
                                    @*<small class="text-muted">@item.CateName</small>*@
                                    <a>
                                        <h3 class="h6 text-uppercase no-margin-bottom">@item.product_name</h3>
                                    </a>
                                    <span class="price text-muted">@item.price.GetValueOrDefault(0).ToString("N0")<sup>đ</sup></span>
                                </div>
                            </div>
                        </div>
                    }
                </div>
                @*@if (ViewBag.TotalPage >= 1)
                    {
                        var pageDisplay = (int)ViewBag.MaxPage;
                        int totalPage = (int)ViewBag.TotalPage;
                        int currentPage = ((int)ViewBag.Page);

                        // Create numeric links
                        var startPageIndex = Math.Max(1, currentPage - pageDisplay / 2);
                        var endPageIndex = Math.Min(totalPage, currentPage + pageDisplay / 2);

                        var link = "/san-pham/" + category.MetaTitle + "-" + category.ID;
                        <nav aria-label="page navigation example" class="d-flex justify-content-center">
                            <ul class="pagination pagination-custom">
                                <li class="page-item"><a href="@link?page=@ViewBag.First" aria-label="Previous" class="page-link"><span aria-hidden="true">Prev</span><span class="sr-only">Previous</span></a></li>
                                @for (int i = startPageIndex; i <= endPageIndex; i++)
                                {
                                    if (currentPage == i)
                                    {
                                        <li class="page-item"> <a href="@link?page=@i" class="page-link active" title="Trang @i">@i</a></li>
                                    }
                                    else
                                    {
                                        <li class="page-item"><a href="@link?page=@i" title="Trang @i" class="page-link">@i</a></li>
                                    }
                                }
                                <li class="page-item"> <a href="@link?page=@ViewBag.Last" class="page-link"> <span aria-hidden="true">Next</span><span class="sr-only">Next</span></a></li>
                            </ul>
                        </nav>
                    }
                    else
                    {
                        <span>Không có bản ghi nào</span>
                    }*@
            </div>
            <!-- / Grid End-->
        </div>
    </div>
    <!--Modal dialog-->
    @foreach (var item in Model)
    {
        <div id="@item.product_id" tabindex="-1" role="dialog" aria-hidden="true" class="modal fade overview">
            <div role="document" class="modal-dialog">
                <div class="modal-content">
                    <button type="button" data-dismiss="modal" aria-label="Close" class="close"><span aria-hidden="true"><i class="icon-close"></i></span></button>
                    <div class="modal-body">
                        <div class="ribbon-primary text-uppercase">Sale</div>
                        <div class="row d-flex align-items-center">
                            <div class="image col-lg-5"><img src="@item.image" alt="..." class="img-fluid d-block"></div>
                            <div class="details col-lg-7">
                                <h2>@item.product_name</h2>
                                <ul class="price list-inline">
                                    <li class="list-inline-item current">@item.price.GetValueOrDefault(0).ToString("N0")<sub>đ</sub></li>
                                </ul>
                                <p>@*@item.Description*@ Mô tả sản phẩm</p>
                                <ul class="CTAs list-inline">
                                    <li class="list-inline-item">
                                        <a href="/them-vao-gio-hang?productId=@item.product_id&quantity=1" class="btn btn-template wide"> <i class="fa fa-shopping-cart"></i>Thêm vào giỏ hàng</a>
                                    </li>
                                    @*<li class="list-inline-item">
                                        <a href="#" class="visit-product active btn btn-template-outlined wide"> <i class="icon-heart"></i>Yêu thích</a>
                                    </li>*@
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</main>

